name: mydokter_rsbk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  animations: ^2.0.7
  appbar_animated: ^0.0.3
  autocomplete_textfield: ^2.0.1
  avatar_glow: ^2.0.2
  floating_action_bubble: ^1.1.4
  awesome_dialog: ^2.2.0
  awesome_drawer_bar: ^1.0.0
  modal_bottom_sheet: 2.1.2
  particles_flutter: ^0.1.4
  checkbox_grouped: ^2.0.0
  in_app_update: ^4.1.4
  smartrefresh: ^0.0.2
  pull_to_refresh_notification: ^3.0.1
  diamond_bottom_bar: ^1.0.0
  shimmer_animation: ^2.1.0
  pull_to_refresh: ^2.0.0
  liquid_pull_to_refresh: ^3.0.1
  badges: ^2.0.3
  bubble_tab_indicator: ^0.1.6
  build_runner: ^2.2.0
  launch_review: ^3.0.1
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.1
  file_picker: ^5.3.3
  calendar_timeline: ^1.1.1
  carousel_slider: ^4.1.1
  coordinator_layout: ^1.0.0+1
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.7.4
  dio: ^4.0.6
  search_page: ^2.3.0
  dropdown_button2: ^1.4.0
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  flutter_speed_dial: ^3.0.5
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  # flutter_dash: ^0.0.1
  flutter_easyloading: ^3.0.0
  # flutter_html: ^0.11.1
  flutter_icons_null_safety: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_pdfview: ^1.3.1
  path_provider: ^2.0.15
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.0
  flutter_tts: ^3.2.2
  fluttertoast: ^8.2.2
  font_awesome_flutter: null
  get: 4.6.5
  get_storage: ^2.1.1
  google_api_headers: ^1.3.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.2.0
  highlight_text: ^1.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  horizontal_calendar: ^1.1.2
  # http: ^0.13.5
  im_stepper: ^0.1.3
  image_picker: ^0.8.5+3
  intl: ^0.18.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  lottie: ^1.2.1
  # package_info_plus: ^1.4.2
  provider: ^6.0.3
  qr_code_scanner: ^1.0.1
  quickalert: ^1.0.1
  shared_preferences: ^2.0.13
  speech_to_text: ^6.1.1
  syncfusion_flutter_charts: ^21.1.38
  text_scroll: ^0.1.2
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
